// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZfbNGRaUQW-l4-xq2IMyu_SUXOR4M8I',
    appId: '1:37658256206:web:f86ab0399aea9e1b56b41f',
    messagingSenderId: '37658256206',
    projectId: 'sazu-market',
    authDomain: 'sazu-market.firebaseapp.com',
    storageBucket: 'sazu-market.firebasestorage.app',
    measurementId: 'G-5T01LMGNDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9COxshFb-9hyHzI6VgfFcjM638bmsNw',
    appId: '1:67442890500:android:2b83787c47c1d55f65a251',
    messagingSenderId: '67442890500',
    projectId: 'fir-app-93058',
    databaseURL: 'https://fir-app-93058-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-93058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBznjzMWbmbMMuCJIk1sAw6SerPwER7UrM',
    appId: '1:67442890500:ios:ec96ccc772a1630565a251',
    messagingSenderId: '67442890500',
    projectId: 'fir-app-93058',
    databaseURL: 'https://fir-app-93058-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-93058.firebasestorage.app',
    iosBundleId: 'com.brownfish.ustahubb',
  );

}