// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  FirebaseOptions getOptions() {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    return _getOptionsForFlavor();
  }

 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyEwx6jcjl2EbrZ_T8oQDbcK3B4HtU7nE',
    appId: '1:37658256206:android:967251596586c4da56b41f',
    messagingSenderId: '37658256206',
    projectId: 'sazu-market',
    storageBucket: 'sazu-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbiJ0_tKrNsN0PhahpX7Ucssd8kPfNN4',
    appId: '1:37658256206:ios:3270033dc38af9ce56b41f',
    messagingSenderId: '37658256206',
    projectId: 'sazu-market',
    storageBucket: 'sazu-market.firebasestorage.app',
    iosBundleId: 'com.asoschi.sazu-market',
  );

  FirebaseOptions _getOptionsForFlavor() {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }
}
